services:
  scraper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:0
    volumes:
      - ./output:/app/output
    networks:
      - scraper-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - scraper-net

volumes:
  mysql-data:

networks:
  scraper-net: